stages:
  - test
  - coverage

# Default docker image to run the jobs
image: python:3.14

test_build:
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt pytest
  script:
    - pytest Tests/ -q
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"

test_coverage:
  stage: coverage
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt pytest coverage
  script:
    - coverage run -m pytest Tests/
    - coverage report
  coverage: '/TOTAL.*\s+(\d+)\%/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
