"""
Tests for Logic_AI_Context — DB-backed prompt/rules, HLT parsing, source
context, message assembly, and low-level output writing. Pure logic, no Qt.
"""
import os
import sys

sys.path.append(os.path.abspath("src"))

import pytest
from Application_Logic import Logic_AI_Context as ctx


class FakeDB:
    """Minimal stand-in for ProjectDatabase meta storage."""
    def __init__(self, open_=True):
        self.is_open = open_
        self._meta = {}

    def get_meta(self, key, default=None):
        return self._meta.get(key, default)

    def set_meta(self, key, value):
        self._meta[key] = value


SAMPLE_HLT = """# Test Case Design - ModelA

This document contains the generated test cases for the **ModelA** architecture model.

---
## Test Case: TC.001 - Temperature read

Given the ECU is running
When IfTemp is read
Then the value is valid

### Low Level Test Case Design
*(Paste the low-level test cases generated by GitHub Copilot here)*

---
## Test Case: TC.002 - Speed read

Given the ECU is running
When IfSpeed is read
Then the value is valid

### Low Level Test Case Design
*(Paste the low-level test cases generated by GitHub Copilot here)*
"""


# ---------------------------------------------------------------------------
# Prompt / rules DB backing
# ---------------------------------------------------------------------------

def test_defaults_when_no_db():
    assert ctx.get_prompt(None) == ctx.DEFAULT_PROMPT
    assert ctx.get_rules(None) == ctx.DEFAULT_RULES


def test_default_prompt_is_deroleplayed():
    # The removed roleplay opener must not be present in the default prompt.
    assert "You are a specialized" not in ctx.DEFAULT_PROMPT
    assert ctx.DEFAULT_PROMPT.startswith("Your task is to generate")


def test_db_roundtrip_prompt_rules():
    db = FakeDB()
    # Falls back to defaults before anything is stored.
    assert ctx.get_prompt(db) == ctx.DEFAULT_PROMPT
    ctx.set_prompt(db, "custom prompt")
    ctx.set_rules(db, "custom rules")
    assert ctx.get_prompt(db) == "custom prompt"
    assert ctx.get_rules(db) == "custom rules"


def test_closed_db_uses_defaults():
    db = FakeDB(open_=False)
    ctx.set_prompt(db, "ignored")  # no-op when closed
    assert ctx.get_prompt(db) == ctx.DEFAULT_PROMPT


# ---------------------------------------------------------------------------
# HLT discovery / parsing
# ---------------------------------------------------------------------------

def test_find_hlt_files(tmp_path):
    (tmp_path / "ModelA_Test_Case_Design.md").write_text("x")
    (tmp_path / "ModelB_Test_Case_Design.md").write_text("y")
    (tmp_path / "rules.md").write_text("z")  # excluded
    found = ctx.find_hlt_files(str(tmp_path))
    assert [os.path.basename(f) for f in found] == [
        "ModelA_Test_Case_Design.md", "ModelB_Test_Case_Design.md"
    ]


def test_find_hlt_files_missing_dir():
    assert ctx.find_hlt_files("/no/such/dir") == []


def test_parse_hlt_file(tmp_path):
    p = tmp_path / "ModelA_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    assert parsed["model_name"] == "ModelA"
    assert len(parsed["test_cases"]) == 2
    tc0 = parsed["test_cases"][0]
    assert tc0["title"] == "TC.001 - Temperature read"
    assert tc0["id"] == "0:TC.001 - Temperature read"
    assert "Given the ECU is running" in tc0["raw"]
    # Placeholder-only -> not yet generated.
    assert tc0["has_lowlevel"] is False


def test_parse_hlt_detects_existing_lowlevel(tmp_path):
    filled = SAMPLE_HLT.replace(
        "*(Paste the low-level test cases generated by GitHub Copilot here)*",
        "1. Set breakpoint...\n2. Run.", 1)
    p = tmp_path / "M_Test_Case_Design.md"
    p.write_text(filled, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    assert parsed["test_cases"][0]["has_lowlevel"] is True
    assert parsed["test_cases"][1]["has_lowlevel"] is False


# ---------------------------------------------------------------------------
# Source context
# ---------------------------------------------------------------------------

def test_build_source_context_scores_and_includes(tmp_path):
    (tmp_path / "temp.c").write_text(
        "void IfTemp_read(void){ int temperature = 5; }", encoding="utf-8")
    (tmp_path / "unrelated.c").write_text(
        "void foo(void){ int bar = 0; }", encoding="utf-8")
    out = ctx.build_source_context(str(tmp_path), ["IfTemp temperature read"], budget_chars=5000)
    assert "temp.c" in out
    assert "IfTemp_read" in out


def test_build_source_context_empty_when_no_source():
    assert ctx.build_source_context("", ["x"]) == ""
    assert ctx.build_source_context("/no/such/path", ["x"]) == ""


def test_build_source_context_respects_budget(tmp_path):
    big = "int x; // keyword padding\n" * 5000
    (tmp_path / "big.c").write_text("keyword\n" + big, encoding="utf-8")
    out = ctx.build_source_context(str(tmp_path), ["keyword"], budget_chars=1000)
    assert len(out) <= 1300  # header + truncated body, bounded


def test_extract_keywords_filters_stopwords_and_short():
    kws = ctx.extract_keywords(["The test shall verify temperature reading"])
    assert "temperature" in kws
    assert "the" not in kws and "test" not in kws  # stopwords
    assert all(len(k) >= 3 for k in kws)


# ---------------------------------------------------------------------------
# Message assembly + output writing
# ---------------------------------------------------------------------------

def test_build_messages():
    msgs = ctx.build_messages("RULES", "PROMPT", "## Test Case: TC.001\nGiven...", "SRC")
    assert msgs[0]["role"] == "system"
    assert "PROMPT" in msgs[0]["content"] and "RULES" in msgs[0]["content"]
    assert msgs[1]["role"] == "user"
    assert "SRC" in msgs[1]["content"]
    assert "TC.001" in msgs[1]["content"]


def test_write_lowlevel_output(tmp_path):
    parsed = ctx.parse_hlt_file_from_text(SAMPLE_HLT) if hasattr(ctx, "parse_hlt_file_from_text") else None
    # parse via file (no text helper) for portability
    p = tmp_path / "ModelA_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    cases = parsed["test_cases"]
    generated = {cases[0]["id"]: "1. Set breakpoint in IfTemp_read.\n2. Run."}
    out_path = ctx.write_lowlevel_output(
        str(tmp_path), parsed["model_name"], parsed["title"], cases, generated)
    assert os.path.basename(out_path) == "ModelA_LowLevel.md"
    content = open(out_path, encoding="utf-8").read()
    assert "Low-Level Test Case Design - ModelA" in content
    assert "Set breakpoint in IfTemp_read" in content
    # Only the generated case is included.
    assert "TC.001" in content
    assert "TC.002" not in content
    # Placeholder text must not leak through.
    assert "Paste the low-level" not in content


def test_clean_generated_strips_echoed_header():
    assert ctx.clean_generated("### Low Level Test Case Design\n\n1. Step") == "1. Step"
    assert ctx.clean_generated("1. Step") == "1. Step"
    assert ctx.clean_generated("```markdown\n1. Step\n```") == "1. Step"


def test_write_lowlevel_no_duplicate_header(tmp_path):
    p = tmp_path / "ModelA_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    cases = parsed["test_cases"]
    # Model echoes the header back, as real models do.
    gen = {cases[0]["id"]: "### Low Level Test Case Design\n\n1. Set breakpoint."}
    out_path = ctx.write_lowlevel_output(
        str(tmp_path), parsed["model_name"], parsed["title"], cases, gen)
    content = open(out_path, encoding="utf-8").read()
    assert content.count(ctx.LOWLEVEL_HEADER) == 1  # exactly one, no duplicate


def test_apply_lowlevel_no_duplicate_header(tmp_path):
    p = tmp_path / "M_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    gen = {parsed["test_cases"][0]["id"]:
           "### Low Level Test Case Design\n\n1. Step."}
    ctx.apply_lowlevel_to_hlt(str(p), gen)
    text = p.read_text(encoding="utf-8")
    # First case: one header (the original), placeholder replaced by steps only.
    assert "### Low Level Test Case Design\n\n### Low Level" not in text
    assert "1. Step." in text


def test_apply_lowlevel_to_hlt_fills_placeholder(tmp_path):
    p = tmp_path / "ModelA_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    cases = parsed["test_cases"]
    generated = {cases[0]["id"]: "1. Set breakpoint.\n2. Run."}
    n = ctx.apply_lowlevel_to_hlt(str(p), generated)
    assert n == 1
    text = p.read_text(encoding="utf-8")
    assert "1. Set breakpoint." in text
    # Case 0 placeholder gone; case 1 placeholder remains.
    assert text.count("Paste the low-level") == 1
    # The high-level structure is preserved.
    assert "## Test Case: TC.001 - Temperature read" in text
    assert "## Test Case: TC.002 - Speed read" in text


def test_apply_lowlevel_idempotent(tmp_path):
    p = tmp_path / "M_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    parsed = ctx.parse_hlt_file(str(p))
    gen = {parsed["test_cases"][0]["id"]: "STEPS"}
    assert ctx.apply_lowlevel_to_hlt(str(p), gen) == 1
    # Second run: placeholder already filled -> nothing changes.
    assert ctx.apply_lowlevel_to_hlt(str(p), gen) == 0
    assert p.read_text(encoding="utf-8").count("STEPS") == 1


def test_apply_lowlevel_no_match(tmp_path):
    p = tmp_path / "M_Test_Case_Design.md"
    p.write_text(SAMPLE_HLT, encoding="utf-8")
    before = p.read_text(encoding="utf-8")
    assert ctx.apply_lowlevel_to_hlt(str(p), {"99:nope": "x"}) == 0
    assert p.read_text(encoding="utf-8") == before


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
