"""
Light construction smoke test for the AI Generation tab controller.

UI behaviour is manual-tested, but this catches import/build errors (so a broken
widget tree can't silently ship). It builds the real Ui_MainWindow, constructs
the controller, and exercises the no-network paths (tree population, prefs).
"""
import os
import sys

sys.path.append(os.path.abspath("src"))

from PyQt6.QtWidgets import QApplication, QMainWindow
app = QApplication.instance() or QApplication(sys.argv)

import UI
import pytest
from UI.tab_ai_generation import AIGenerationController


@pytest.fixture(autouse=True)
def _isolate_credentials(tmp_path, monkeypatch):
    """Point the AI credential store at a temp dir so the smoke test never reads
    the real per-user store (which may hold a live Copilot token and would
    trigger real-network model discovery)."""
    monkeypatch.setenv("ARCHVALIDATOR_CONFIG_DIR", str(tmp_path))


def _window():
    win = QMainWindow()
    win.ui = UI.Ui_MainWindow()
    win.ui.setupUi(win)
    win.current_project_file = None
    win.project_db = None
    win.edit_mode = True
    return win


def test_controller_constructs_and_adds_tab():
    win = _window()
    before = win.ui.tabWidget.count()
    ctrl = AIGenerationController(win)
    assert win.ui.tabWidget.count() == before + 1
    # Tab title present
    titles = [win.ui.tabWidget.tabText(i) for i in range(win.ui.tabWidget.count())]
    assert "AI Test Generation" in titles


def test_provider_combo_populates():
    win = _window()
    ctrl = AIGenerationController(win)
    ctrl._refresh_providers()
    # All four providers listed.
    datas = [ctrl.cmb_provider.itemData(i) for i in range(ctrl.cmb_provider.count())]
    assert set(datas) == {"copilot", "anthropic", "openai", "gemini"}


def test_hlt_empty_state(tmp_path):
    win = _window()
    win.current_project_file = str(tmp_path / "p.arch")
    ctrl = AIGenerationController(win)
    ctrl.refresh_hlt_files()
    # No 'Test Case Design' folder -> the placeholder entry is shown.
    assert ctrl.cmb_hlt.count() == 1
    assert ctrl.cmb_hlt.itemData(0) is None


def test_tree_populates_from_hlt(tmp_path):
    # Create a fake project with a generated HLT file.
    proj_dir = tmp_path
    tcd = proj_dir / "Test Case Design"
    tcd.mkdir()
    (tcd / "ModelA_Test_Case_Design.md").write_text(
        "# Test Case Design - ModelA\n\n"
        "---\n## Test Case: TC.001 - x\nGiven a\nWhen b\nThen c\n\n"
        "### Low Level Test Case Design\n"
        "*(Paste the low-level test cases generated by GitHub Copilot here)*\n",
        encoding="utf-8")
    win = _window()
    win.current_project_file = str(proj_dir / "p.arch")
    ctrl = AIGenerationController(win)
    ctrl.refresh_hlt_files()
    # One real HLT file selected, tree has the model + one test case.
    assert ctrl.cmb_hlt.count() == 1
    root = ctrl.tree.topLevelItem(0)
    assert root is not None
    assert root.childCount() == 1
    assert ctrl._selected_cases()[0]["title"] == "TC.001 - x"


if __name__ == "__main__":
    import pytest
    raise SystemExit(pytest.main([__file__, "-v"]))
