# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1762, 1155)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_tiitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_tiitle.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_tiitle.setFont(font)
        self.lbl_tiitle.setObjectName("lbl_tiitle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1762, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mnu_About = QtGui.QAction(parent=MainWindow)
        self.mnu_About.setObjectName("mnu_About")
        self.actionOpen_ELF = QtGui.QAction(parent=MainWindow)
        self.actionOpen_ELF.setObjectName("actionOpen_ELF")
        self.actionOpen_Json = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Json.setObjectName("actionOpen_Json")
        self.mnu_New_Project = QtGui.QAction(parent=MainWindow)
        self.mnu_New_Project.setObjectName("mnu_New_Project")
        self.mnu_Load_Project = QtGui.QAction(parent=MainWindow)
        self.mnu_Load_Project.setObjectName("mnu_Load_Project")
        self.menuFile.addAction(self.mnu_New_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.mnu_Load_Project)
        self.menuFile.addSeparator()
        self.menuAbout.addAction(self.mnu_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Architecture Testing Tool"))
        self.lbl_tiitle.setText(_translate("MainWindow", "Architecture Testing Tool"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.mnu_About.setText(_translate("MainWindow", "About"))
        self.actionOpen_ELF.setText(_translate("MainWindow", "Open ELF"))
        self.actionOpen_Json.setText(_translate("MainWindow", "Open Json"))
        self.mnu_New_Project.setText(_translate("MainWindow", "New Project"))
        self.mnu_Load_Project.setText(_translate("MainWindow", "Load Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
