# Form implementation generated from reading ui file 'win_help_new_project.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_win_help_new_project(object):
    def setupUi(self, Help_New_Project):
        Help_New_Project.setObjectName("Help_New_Project")
        Help_New_Project.resize(464, 313)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.HelpAbout)
        Help_New_Project.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Help_New_Project)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Text_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Text_1.setGeometry(QtCore.QRect(7, 60, 451, 61))
        font = QtGui.QFont()
        font.setBold(False)
        self.lbl_Text_1.setFont(font)
        self.lbl_Text_1.setScaledContents(False)
        self.lbl_Text_1.setWordWrap(True)
        self.lbl_Text_1.setObjectName("lbl_Text_1")
        self.lbl_Text_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Text_2.setGeometry(QtCore.QRect(7, 110, 451, 111))
        self.lbl_Text_2.setWordWrap(True)
        self.lbl_Text_2.setObjectName("lbl_Text_2")
        self.btn_close_window = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_close_window.setGeometry(QtCore.QRect(162, 220, 141, 41))
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.WindowClose)
        self.btn_close_window.setIcon(icon)
        self.btn_close_window.setObjectName("btn_close_window")
        self.lbl_Title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Title.setGeometry(QtCore.QRect(140, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lbl_Title.setFont(font)
        self.lbl_Title.setObjectName("lbl_Title")
        Help_New_Project.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Help_New_Project)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 24))
        self.menubar.setObjectName("menubar")
        Help_New_Project.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Help_New_Project)
        self.statusbar.setObjectName("statusbar")
        Help_New_Project.setStatusBar(self.statusbar)

        self.retranslateUi(Help_New_Project)
        QtCore.QMetaObject.connectSlotsByName(Help_New_Project)

    def retranslateUi(self, Help_New_Project):
        _translate = QtCore.QCoreApplication.translate
        Help_New_Project.setWindowTitle(_translate("Help_New_Project", "Help"))
        self.lbl_Text_1.setText(_translate("Help_New_Project", "To ensure the best performance, it is highly recommended to initialize your project using an existing JSON configuration."))
        self.lbl_Text_2.setText(_translate("Help_New_Project", "Loading a new ELF file directly can take up to 10 minutes. You can always update or check for changes in your ELF file once the project is open by using the \"Compare with ELF\" feature. This avoids the long initial wait time."))
        self.btn_close_window.setText(_translate("Help_New_Project", "Close Window"))
        self.lbl_Title.setText(_translate("Help_New_Project", "Help New Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help_New_Project = QtWidgets.QMainWindow()
    ui = Ui_Help_New_Project()
    ui.setupUi(Help_New_Project)
    Help_New_Project.show()
    sys.exit(app.exec())
