# Form implementation generated from reading ui file 'win_simple_loading.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Standard_Loading(object):
    def setupUi(self, Standard_Loading):
        Standard_Loading.setObjectName("Standard_Loading")
        Standard_Loading.resize(394, 258)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.AppointmentSoon)
        Standard_Loading.setWindowIcon(icon)
        self.lbl_loading_text = QtWidgets.QLabel(parent=Standard_Loading)
        self.lbl_loading_text.setGeometry(QtCore.QRect(80, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lbl_loading_text.setFont(font)
        self.lbl_loading_text.setObjectName("lbl_loading_text")
        self.lbl_icon_loading = QtWidgets.QLabel(parent=Standard_Loading)
        self.lbl_icon_loading.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.lbl_icon_loading.setText("")
        self.lbl_icon_loading.setObjectName("lbl_icon_loading")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Standard_Loading)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 90, 351, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.plainTextEdit.setLineWidth(3)
        self.plainTextEdit.setMidLineWidth(0)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Standard_Loading)
        QtCore.QMetaObject.connectSlotsByName(Standard_Loading)

    def retranslateUi(self, Standard_Loading):
        _translate = QtCore.QCoreApplication.translate
        Standard_Loading.setWindowTitle(_translate("Standard_Loading", "Loading"))
        self.lbl_loading_text.setText(_translate("Standard_Loading", "Loading please wait..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Standard_Loading = QtWidgets.QDialog()
    ui = Ui_Standard_Loading()
    ui.setupUi(Standard_Loading)
    Standard_Loading.show()
    sys.exit(app.exec())
