# Form implementation generated from reading ui file 'win_new_project_dialogue.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_win_new_project_dialogue(object):
    def setupUi(self, win_new_project_dialogue):
        win_new_project_dialogue.setObjectName("win_new_project_dialogue")
        win_new_project_dialogue.resize(530, 269)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.FolderNew)
        win_new_project_dialogue.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=win_new_project_dialogue)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_help_new_project = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_help_new_project.setGeometry(QtCore.QRect(363, 160, 141, 51))
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DialogQuestion)
        self.btn_help_new_project.setIcon(icon)
        self.btn_help_new_project.setObjectName("btn_help_new_project")
        self.lbl_question_dialog = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_question_dialog.setGeometry(QtCore.QRect(10, 0, 531, 181))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.lbl_question_dialog.setFont(font)
        self.lbl_question_dialog.setObjectName("lbl_question_dialog")
        self.btn_new_elf = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_new_elf.setGeometry(QtCore.QRect(26, 160, 141, 51))
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DocumentNew)
        self.btn_new_elf.setIcon(icon)
        self.btn_new_elf.setObjectName("btn_new_elf")
        self.btn_Load_json = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Load_json.setGeometry(QtCore.QRect(195, 160, 141, 51))
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DocumentOpen)
        self.btn_Load_json.setIcon(icon)
        self.btn_Load_json.setObjectName("btn_Load_json")
        win_new_project_dialogue.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=win_new_project_dialogue)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 24))
        self.menubar.setObjectName("menubar")
        win_new_project_dialogue.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=win_new_project_dialogue)
        self.statusbar.setObjectName("statusbar")
        win_new_project_dialogue.setStatusBar(self.statusbar)

        self.retranslateUi(win_new_project_dialogue)
        QtCore.QMetaObject.connectSlotsByName(win_new_project_dialogue)

    def retranslateUi(self, win_new_project_dialogue):
        _translate = QtCore.QCoreApplication.translate
        win_new_project_dialogue.setWindowTitle(_translate("win_new_project_dialogue", "New Project"))
        self.btn_help_new_project.setText(_translate("win_new_project_dialogue", "Help"))
        self.lbl_question_dialog.setText(_translate("win_new_project_dialogue", "Start from an existing data base?"))
        self.btn_new_elf.setText(_translate("win_new_project_dialogue", "Load New ELF"))
        self.btn_Load_json.setText(_translate("win_new_project_dialogue", "Load JSON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_new_project_dialogue = QtWidgets.QMainWindow()
    ui = Ui_win_new_project_dialogue()
    ui.setupUi(win_new_project_dialogue)
    win_new_project_dialogue.show()
    sys.exit(app.exec())
